name: deploy

on: 
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "./_site/*"
        target: "/home/el/site"
