name: deploy

on: 
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        rm: true
        strip_components: true
        source: "_site"
        target: "${{ secrets.REMOTE_DIR }}"
        
